name: sm-gs
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch==2.1.2
  - torchvision==0.16.2
  - pytorch-cuda=11.8
  - pip:
    - numpy<2
    - torch-scatter
    - opencv-python
    - einops        
    - colorama     
    - tqdm
    - plyfile
    - scikit-learn
    - scipy
    - lpips
    - matplotlib
    - argparse
    - wheel
    - typing_extensions