name: sm-gs
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cudatoolkit
  - pytorch==2.1.2
  - torchvision==0.16.2
  - pytorch-cuda=11.8
  - pip:
    - tqdm
    - plyfile
    - scikit-learn
    - scipy
    - lpips
    - matplotlib
    - argparse
    - wheel
    - typing_extensions
    - wandb 